# Meta Data for SEO

## Homepage
title = "e2immu"
titleSeparator = "-"
titleAddition = "A static code analyser for Java focusing on modification and immutability."
description = "e2immu is a static code analyser for Java focusing on modification and immutability."

## Open Graph + Twitter Cards
images = ["doks.png"]
twitterSite = "e2immu.org"
twitterCreator = "e2immu.org"
facebookAuthor = "xxx"
facebookPublisher = "xxx"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo-doks.png"
schemaTwitter = "https://twitter.com/e2immu.org"
schemaLinkedIn = "xxx"
schemaGitHub = "https://github.com/e2immu"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://github.com/\">GitHub</a>, <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://getdoks.org/\">Doks</a>"

# Alert
alert = false
#alertText = "Like e2immu? <a class=\"alert-link\" href=\"https://github.com/h-enk/doks/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/e2immu/e2immu-site"
editPage = true

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = false
  breadCrumb = false
  highLight = true
  kaTex = false
